### ISSUE TITLE
How about for buttons to reset the :focus and user-select?

### ISSUE THREAD

**Issue by kaaboeld** [filipelinhares/sanilize.css#10]
```
button{
  user-select:none;
}
button:focus{
  outline:0;
}
```

**Comment by filipelinhares** [comment]
Thanks for your suggestion @kaaboeld.

``` css
button:focus {
  outline: 0;
}
```

Outline on focus is very important for keyboard users, low-sighted users, and other accessibility technology. **We won't add this.**

---

``` css
button {
  user-select:none;
}
```

 ["Is `user-select: none` bad UX?"](http://ux.stackexchange.com/questions/83184/is-user-select-none-bad-ux).

This sounds good.

**I'll keep this issue open for feedback.**
