### ISSUE TITLE
button:active color property is not reset

### ISSUE THREAD

**Issue by AndrewPrifer** [filipelinhares/sanilize.css#18]
button:active color property is not reset. This is problematic in Safari which uses

```css
input:matches([type="button"], [type="submit"], [type="reset"]):active, input[type="file"]::-webkit-file-upload-button:active, button:active {
  color: activebuttontext;
}
```

where activebuttontext is code for `white`.
