### ISSUE TITLE
Button color

### ISSUE THREAD

**Issue by jeanmatthieud** [filipelinhares/sanilize.css#28]
The button style adds a "color: inherit" property, which adds complexity to style the button

```css
/* Apply cursor pointer to button elements */
button,
[type='button'],
[type='reset'],
[type='submit'],
[role='button'] {
  cursor: pointer;
  color: inherit;
}
```
